# MicrosoftCN - Plain domain list for SmartDNS
# Total domains: 36

aadrm.cn
attachments.office365-net.cn
auth.microsoft.cn
azure-mobile.cn
azure.cn
chinacloud-mobile.cn
chinacloudapi.cn
graph.chinacloudapi.us
login.partner.microsoftonline.cn
loki.office365.cn
microsoftgraph.chinacloudapi.cn
microsoftonline.cn
msauth.cn
msauthimages.cn
msftauth.cn
msftauthimages.cn
officewebapps.cn
onmschina.cn
partner.lync.cn
partner.microsoftonline-m-i.net.cn
partner.microsoftonline-m.net.cn
partner.microsoftonline-p.cn
partner.microsoftonline-p.net.cn
partner.microsoftonline.cn
partner.office365.cn
partner.officewebapps.cn
partner.outlook.cn
portal.partner.microsoftonline.cdnsvc.com
r4.partner.outlook.cn
sharepoint.cn
sovcloud-mx.cn
sovcloud-static.cn
sovcloud-usercontent.cn
sovcloud.cn
teams.microsoftonline.cn
windowsazure.cn
